site_name: FaBo EdgeAI Docs
theme:
    name: material
    language: 'ja'
extra:
    search:
        language: 'jp'
markdown_extensions:
  - fontawesome_markdown
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
      pygments_style: monokai
      linenums: true
  - markdown_fenced_code_tabs
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"  
  - 'stylesheets/extra.css'
plugins:
  - macros